# Generated by Django 5.1.2 on 2024-11-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
