# Generated by Django 5.1.2 on 2024-11-24 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_appuser_balance_alter_appuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
