# Generated by Django 5.1.2 on 2024-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_appuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
