# Generated by Django 5.1.2 on 2024-11-25 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="purchased_at",
        ),
    ]
