# Generated by Django 5.1.2 on 2024-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_stock_purchased_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
