# Generated by Django 5.1.2 on 2024-11-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_appuser_initial_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("ticker", models.CharField(max_length=10)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("percent_change", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "unique_together": {("user_email", "ticker")},
            },
        ),
    ]
