# Generated by Django 5.1.2 on 2024-11-27 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="percent_change",
        ),
    ]
