# Generated by Django 5.1.2 on 2024-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_watchlist_current_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="initial_balance",
        ),
    ]
